import assert from 'node:assert/strict';
import { serializeCampaignState,deserializeCampaignState,saveCampaignState,loadCampaignState } from '../src/systems/save-state-v2.mjs';
const state={currentLevelId:'3-2-canyon-cliffs',unlocked:new Set(['1-1-sprout-steps','3-2-canyon-cliffs']),completed:new Set(['1-1-sprout-steps']),bossesDefeated:new Set(['overgrown-guardian']),percent:5};
const restored=deserializeCampaignState(serializeCampaignState(state));
assert.equal(restored.currentLevelId,state.currentLevelId);
assert.equal(restored.unlocked.has('3-2-canyon-cliffs'),true);
const map=new Map();const storage={setItem:(k,v)=>map.set(k,v),getItem:(k)=>map.get(k)||null};
saveCampaignState(storage,state);const loaded=loadCampaignState(storage,null);assert.equal(loaded.bossesDefeated.has('overgrown-guardian'),true);
assert.throws(()=>deserializeCampaignState(JSON.stringify({version:'seed-man-save-v2',currentLevelId:'1-1',unlocked:'bad',completed:[],bossesDefeated:[],percent:5})),/unlocked/);
assert.throws(()=>deserializeCampaignState(JSON.stringify({version:'seed-man-save-v2',currentLevelId:'1-1',unlocked:[],completed:[],bossesDefeated:[],percent:150})),/percent/);
assert.throws(()=>deserializeCampaignState(JSON.stringify({version:'seed-man-save-v1',currentLevelId:'1-1',unlocked:[],completed:[],bossesDefeated:[],percent:5})),/version/);
const fallback={safe:true};
assert.equal(deserializeCampaignState('{bad json',{fallback}),fallback);
console.log('Seed Man save state v2 OK');
