<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store, max-age=0');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: same-origin');

const BOB_TTL = 14400;
const BOB_MAX_PLAYERS = 10;
const BOB_MIN_PLAYERS = 2;
const BOB_VOTE_OPTIONS = [15,24,35,45,0];
const BOB_REVEAL_OPTIONS = [6,9,12,20];
const BOB_ROUND_OPTIONS = [8,12,16,20];

function out(array $p,int $s=200):void{http_response_code($s);echo json_encode($p,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function fail(string $m,int $s=400):void{out(['error'=>$m],$s);}
function body():array{$d=json_decode(file_get_contents('php://input')?:'{}',true);if(!is_array($d))fail('Invalid JSON body.');return $d;}
function now_ms():int{return (int)round(microtime(true)*1000);}
function rid(int $b=12):string{return rtrim(strtr(base64_encode(random_bytes($b)),'+/','-_'),'=');}
function cut(string $v,int $n):string{return function_exists('mb_substr')?mb_substr($v,0,$n):substr($v,0,$n);}
function clean_name($v):string{$s=trim(preg_replace('/[\x00-\x1F\x7F]/u','',strval($v)));if($s==='')fail('Player name is required.');return cut($s,24);}
function clean_text($v):string{$s=trim(preg_replace('/[\x00-\x1F\x7F]/u',' ',strval($v)));return cut($s,240);}
function code6($v):string{$s=strtoupper(trim(strval($v)));if(!preg_match('/^[A-Z0-9]{6}$/',$s))fail('A valid 6-character room code is required.');return $s;}
function room_code():string{$a='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';$s='';for($i=0;$i<6;$i++)$s.=$a[random_int(0,strlen($a)-1)];return $s;}

$root=dirname(__DIR__,2).'/wp-load.php';$useWp=is_file($root);if($useWp)require_once $root;
function store_get(string $k){global $useWp;if($useWp)return get_transient($k);$p=sys_get_temp_dir().'/'.$k.'.json';if(!is_file($p))return false;$d=json_decode(file_get_contents($p),true);if(!is_array($d)||($d['_expires']??0)<time()){@unlink($p);return false;}unset($d['_expires']);return $d;}
function store_set(string $k,array $v,int $ttl=BOB_TTL):void{global $useWp;if($useWp){set_transient($k,$v,$ttl);return;}$v['_expires']=time()+$ttl;file_put_contents(sys_get_temp_dir().'/'.$k.'.json',json_encode($v),LOCK_EX);}
function room_get(string $c):array{$r=store_get('bob2_room_'.$c);if(!$r)fail('Room not found or expired.',404);return $r;}
function room_save(array &$r):void{$r['updatedAt']=now_ms();$r['revision']=intval($r['revision']??0)+1;store_set('bob2_room_'.$r['code'],$r);foreach($r['players'] as $p)store_set('bob2_player_'.$p['id'],['code'=>$r['code'],'token'=>$p['token']],BOB_TTL);}
function with_lock(string $code,callable $fn){$path=sys_get_temp_dir().'/bob2_lock_'.$code.'.lck';$h=fopen($path,'c');if(!$h)fail('Room lock unavailable.',503);if(!flock($h,LOCK_EX))fail('Room lock unavailable.',503);try{return $fn();}finally{flock($h,LOCK_UN);fclose($h);}}
function presence_touch(string $id):void{store_set('bob2_presence_'.$id,['seen'=>now_ms()],90);}
function presence_alive(string $id):bool{return store_get('bob2_presence_'.$id)!==false;}
function rate_limit(string $scope,int $limit,int $seconds):void{$ip=$_SERVER['REMOTE_ADDR']??'unknown';$key='bob2_rl_'.$scope.'_'.substr(hash('sha256',$ip),0,20);$r=store_get($key);$count=is_array($r)?intval($r['count']??0):0;if($count>=$limit)fail('Too many requests. Try again shortly.',429);store_set($key,['count'=>$count+1],$seconds);}

function cards():array{return [
['id'=>'BOB-001','name'=>'Purple Monkey Balls','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Mendo Purps × Deep Chunk background','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-002','name'=>'Cat Piss','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Old-school clone background','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-003','name'=>'Crouching Tiger Hidden Alien','answer'=>'BUD','difficulty'=>'Hard','clue'=>"Tiger's Milk × Starfighter",'reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-004','name'=>'Slap N Tickle','answer'=>'BUD','difficulty'=>'Hard','clue'=>'GMO × Grape Pie','reality'=>'Documented as a real cannabis strain name.','source'=>'SeedFinder + Weedmaps'],
['id'=>'BOB-005','name'=>'Dog Shit','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Old-school legendary line','reality'=>'Documented as a real cannabis strain name.','source'=>'SeedFinder'],
['id'=>'BOB-006','name'=>'Donkey Butter','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Grease Monkey family','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-007','name'=>'Meat Breath','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Meatloaf × Mendo Breath family','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-008','name'=>'Unicorn Poop','answer'=>'BUD','difficulty'=>'Hard','clue'=>'GMO × Sophisticated Lady family','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-009','name'=>'Peanut Butter Breath','answer'=>'BUD','difficulty'=>'Easy','clue'=>'Do-Si-Dos × Mendo Breath family','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-010','name'=>'Garlic Breath','answer'=>'BUD','difficulty'=>'Medium','clue'=>'GMO / Breath-family naming lane','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-011','name'=>'Duct Tape','answer'=>'BUD','difficulty'=>'Medium','clue'=>'GG4 × Do-Si-Dos style lineage','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly'],
['id'=>'BOB-012','name'=>'Alaskan Thunder Fuck','answer'=>'BUD','difficulty'=>'Easy','clue'=>'Old-school Alaskan / Matanuska family','reality'=>'Documented as a real cannabis strain name, also known as ATF.','source'=>'Leafly'],
['id'=>'BOB-014','name'=>'Jillybean','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Orange Velvet × Space Queen','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-015','name'=>'Afgooey','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Afghani × Maui Haze style background','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-016','name'=>'Poochie Love','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Dogshit clone × Face/Off OG bx1','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-018','name'=>'Monkey Balls','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Purple-family naming lane','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly'],
['id'=>'BOB-020','name'=>"Where's My Bike",'answer'=>'BUD','difficulty'=>'Hard','clue'=>'Amnesia × Biker Kush','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-041','name'=>'Cheetah Piss','answer'=>'BUD','difficulty'=>'Medium','clue'=>'Lemonnade × Gelato 42 × London Pound Cake','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-046','name'=>'Cheese Quake','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Cheese × Querkle','reality'=>'Documented as a real cannabis strain name.','source'=>'Leafly + SeedFinder'],
['id'=>'BOB-060','name'=>'Wet Wet','answer'=>'BUD','difficulty'=>'Hard','clue'=>'Cheetah Piss × Runtz','reality'=>'Documented as a real cannabis strain name.','source'=>'SeedFinder'],
['id'=>'BOB-021','name'=>'Blueberry Parking Lot','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Blueberry Muffin × Asphalt OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-022','name'=>"Grandma's Gas Tank",'answer'=>'BLUFF','difficulty'=>'Hard','clue'=>"Grandpa's Stash × Gas Mask",'reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-023','name'=>'Mango Court Date','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Mango Haze × Jury Duty OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-025','name'=>'Glitter Skunk 91','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Skunk #1 × Glitter Bomb','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-026','name'=>'Runtz of Evidence','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'White Runtz × Witness OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-027','name'=>'Banana Bail Money','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Banana OG × PayDay Kush','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-028','name'=>'Cookies & Confusion','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Forum Cookies × Hazy OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-029','name'=>'Sour Tax Refund','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Sour Diesel × PayDay Kush','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-030','name'=>'Pineapple Probation','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Pineapple Express × Parole OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-031','name'=>'Diesel Pickle Breath','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Sour Diesel × Garlic Breath','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-032','name'=>'Wedding Cake Wreck','answer'=>'BLUFF','difficulty'=>'Easy','clue'=>'Wedding Cake × Trainwreck','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-033','name'=>'Blue Zaza Buffet','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Blue Cookies × Zaza','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-034','name'=>'Grape Custody Battle','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Grape Pie × Divorce Cake','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-036','name'=>'Strawberry Courtroom','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Strawberry Cough × Judge OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-038','name'=>'Turbo Grandpa Haze','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>"Grandpa's Stash × Super Silver Haze",'reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-039','name'=>'Cream Soda Felony','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Cream Soda × Felony Fuel','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-040','name'=>'Alien Lunch Money','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Alien OG × PayDay Kush','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-061','name'=>'Blueberry Bootleg','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Blueberry Muffin × Moonshine OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-067','name'=>'Mango Bench Warrant','answer'=>'BLUFF','difficulty'=>'Medium','clue'=>'Mango Haze × Bench Warrant OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print'],
['id'=>'BOB-076','name'=>'Pineapple Panic Button','answer'=>'BLUFF','difficulty'=>'Hard','clue'=>'Pineapple Express × Anxiety OG','reality'=>'Created for Bud or Bluff; preliminary collision pass found no clear strain match.','source'=>'Game-created / recheck before print']
];}
function shuffle_idx(int $n):array{$a=range(0,$n-1);for($i=$n-1;$i>0;$i--){$j=random_int(0,$i);[$a[$i],$a[$j]]=[$a[$j],$a[$i]];}return $a;}
function player_new(string $name,bool $host):array{return ['id'=>rid(),'token'=>rid(24),'name'=>$name,'host'=>$host,'active'=>true,'score'=>0,'streak'=>0,'bestStreak'=>0,'doubleUsed'=>false,'vote'=>null,'voteDouble'=>false,'joinedAt'=>now_ms()];}
function pidx(array $r,string $id):int{foreach($r['players'] as $i=>$p)if($p['id']===$id)return $i;return -1;}
function auth_room(array $r):int{$pid=$_SERVER['HTTP_X_PLAYER_ID']??'';$tok=$_SERVER['HTTP_X_PLAYER_TOKEN']??'';if(!$pid||!$tok)fail('Player session required.',401);$i=pidx($r,$pid);if($i<0||!hash_equals($r['players'][$i]['token'],$tok))fail('Invalid player session.',401);presence_touch($pid);return $i;}
function active_players(array $r):array{return array_values(array_filter($r['players'],fn($p)=>!empty($p['active'])));}
function all_voted(array $r):bool{foreach($r['players'] as $p)if(!empty($p['active'])&&($p['vote']??null)===null)return false;return count(active_players($r))>=BOB_MIN_PLAYERS;}
function current_card(array $r):array{$deck=cards();$idx=$r['deckOrder'][$r['round']]??null;if($idx===null||!isset($deck[$idx]))fail('Card deck is out of sync.',500);return $deck[$idx];}
function system_msg(array &$r,string $t):void{$r['chat'][]=['id'=>rid(8),'kind'=>'system','text'=>$t,'at'=>now_ms()];if(count($r['chat'])>80)$r['chat']=array_slice($r['chat'],-80);}
function transfer_host(array &$r):void{foreach($r['players'] as &$p)$p['host']=false;unset($p);$new=null;foreach($r['players'] as $i=>$p)if(!empty($p['active'])&&presence_alive($p['id'])){$new=$i;break;}if($new===null)foreach($r['players'] as $i=>$p)if(!empty($p['active'])){$new=$i;break;}if($new!==null){$r['players'][$new]['host']=true;$r['hostId']=$r['players'][$new]['id'];system_msg($r,$r['players'][$new]['name'].' is now the host.');}}
function begin_round(array &$r):void{foreach($r['players'] as &$p){$p['vote']=null;$p['voteDouble']=false;}unset($p);$r['status']='voting';$r['roundSummary']=null;$r['voteEndsAt']=$r['voteSeconds']===0?null:now_ms()+($r['voteSeconds']*1000);$r['revealEndsAt']=null;$r['lastEvent']=['id'=>rid(8),'type'=>'round-start','round'=>$r['round']+1];}
function reveal_round(array &$r):void{if($r['status']!=='voting')return;$c=current_card($r);$bud=0;$bluff=0;$correct=0;$active=0;foreach($r['players'] as &$p){if(empty($p['active']))continue;$active++;if($p['vote']==='BUD')$bud++;if($p['vote']==='BLUFF')$bluff++;$ok=$p['vote']!==null&&$p['vote']===$c['answer'];if($ok)$correct++;$dbl=!empty($p['voteDouble']);$delta=$dbl?($ok?2:-1):($ok?1:0);$p['score']+=$delta;if($ok){$p['streak']++;$p['bestStreak']=max($p['bestStreak'],$p['streak']);}else{$p['streak']=0;}if($dbl)$p['doubleUsed']=true;}unset($p);$r['roundSummary']=['budVotes'=>$bud,'bluffVotes'=>$bluff,'correct'=>$correct,'active'=>$active];$r['status']='reveal';$r['revealStartedAt']=now_ms();$r['revealEndsAt']=$r['autoAdvance']?now_ms()+($r['revealSeconds']*1000):null;$r['lastEvent']=['id'=>rid(8),'type'=>'round-reveal','answer'=>$c['answer'],'round'=>$r['round']+1];}
function finish_game(array &$r,string $reason='complete'):void{$r['status']='finished';$r['finishReason']=$reason;$r['voteEndsAt']=null;$r['revealEndsAt']=null;$r['lastEvent']=['id'=>rid(8),'type'=>'game-finished','reason'=>$reason];}
function next_round(array &$r):void{if($r['status']!=='reveal')return;$r['round']++;if($r['round']>=$r['roundLimit']){finish_game($r);return;}begin_round($r);}
function advance(array &$r):bool{$changed=false;$now=now_ms();if($r['status']==='voting'&&(all_voted($r)||($r['voteEndsAt']!==null&&$r['voteEndsAt']<=$now))){reveal_round($r);$changed=true;}if($r['status']==='reveal'&&$r['autoAdvance']&&$r['revealEndsAt']!==null&&$r['revealEndsAt']<=$now){next_round($r);$changed=true;}return $changed;}
function public_player(array $p,string $status,bool $isMe):array{$x=['id'=>$p['id'],'name'=>$p['name'],'host'=>$p['host'],'active'=>$p['active'],'score'=>$p['score'],'streak'=>$p['streak'],'bestStreak'=>$p['bestStreak'],'doubleAvailable'=>!$p['doubleUsed'],'hasVoted'=>$p['vote']!==null];if($isMe||$status==='reveal'||$status==='finished'){$x['vote']=$p['vote'];$x['usedDouble']=$p['voteDouble'];}return $x;}
function standings(array $ps):array{$a=array_map(fn($p)=>['id'=>$p['id'],'name'=>$p['name'],'score'=>$p['score'],'bestStreak'=>$p['bestStreak'],'active'=>$p['active']],$ps);usort($a,fn($a,$b)=>($b['score']<=>$a['score'])?:($b['bestStreak']<=>$a['bestStreak'])?:strcmp($a['name'],$b['name']));return $a;}
function public_state(array $r,int $me):array{$status=$r['status'];$card=null;if(in_array($status,['voting','reveal'],true)){$c=current_card($r);$card=['id'=>$c['id'],'name'=>$c['name'],'difficulty'=>$c['difficulty'],'clue'=>$c['clue']];if($status==='reveal'){$card['answer']=$c['answer'];$card['reality']=$c['reality'];$card['source']=$c['source'];}}$players=[];foreach($r['players'] as $i=>$p)$players[]=public_player($p,$status,$i===$me);return ['code'=>$r['code'],'status'=>$status,'serverNow'=>now_ms(),'revision'=>$r['revision'],'round'=>$r['round']+1,'roundLimit'=>$r['roundLimit'],'voteSeconds'=>$r['voteSeconds'],'revealSeconds'=>$r['revealSeconds'],'autoAdvance'=>$r['autoAdvance'],'joinLocked'=>$r['joinLocked'],'voteEndsAt'=>$r['voteEndsAt'],'revealEndsAt'=>$r['revealEndsAt'],'hostId'=>$r['hostId'],'me'=>$players[$me],'players'=>$players,'card'=>$card,'roundSummary'=>$r['roundSummary'],'chat'=>$r['chat'],'standings'=>standings($r['players']),'lastEvent'=>$r['lastEvent'],'finishReason'=>$r['finishReason']??null];}
function validate_setting($v,array $allowed,string $label):int{$n=intval($v);if(!in_array($n,$allowed,true))fail('Invalid '.$label.'.');return $n;}

$action=$_GET['action']??'state';if($_SERVER['REQUEST_METHOD']==='OPTIONS')out([],204);
if($action==='create'&&$_SERVER['REQUEST_METHOD']==='POST'){rate_limit('create',6,60);$b=body();$name=clean_name($b['name']??'');$rounds=validate_setting($b['rounds']??12,BOB_ROUND_OPTIONS,'round count');$vote=validate_setting($b['voteSeconds']??24,BOB_VOTE_OPTIONS,'vote timer');$reveal=validate_setting($b['revealSeconds']??9,BOB_REVEAL_OPTIONS,'reveal timer');do{$code=room_code();$exists=store_get('bob2_room_'.$code);}while($exists);$p=player_new($name,true);presence_touch($p['id']);$deck=cards();$r=['code'=>$code,'status'=>'lobby','hostId'=>$p['id'],'players'=>[$p],'round'=>0,'roundLimit'=>min($rounds,count($deck)),'deckOrder'=>shuffle_idx(count($deck)),'voteSeconds'=>$vote,'revealSeconds'=>$reveal,'autoAdvance'=>!isset($b['autoAdvance'])||!empty($b['autoAdvance']),'joinLocked'=>false,'voteEndsAt'=>null,'revealEndsAt'=>null,'roundSummary'=>null,'chat'=>[],'lastEvent'=>null,'revision'=>0,'createdAt'=>now_ms(),'updatedAt'=>now_ms()];system_msg($r,$name.' opened the room.');room_save($r);out(['code'=>$code,'playerId'=>$p['id'],'token'=>$p['token']]);}
if($action==='join'&&$_SERVER['REQUEST_METHOD']==='POST'){rate_limit('join',30,60);$b=body();$code=code6($b['code']??'');$name=clean_name($b['name']??'');$result=with_lock($code,function()use($code,$name){$r=room_get($code);if($r['status']!=='lobby'||!empty($r['joinLocked']))fail('This lobby is locked.');if(count(active_players($r))>=BOB_MAX_PLAYERS)fail('This room is full.');foreach($r['players'] as $p)if(!empty($p['active'])&&strcasecmp($p['name'],$name)===0)fail('That player name is already in this room.');$p=player_new($name,false);presence_touch($p['id']);$r['players'][]=$p;system_msg($r,$name.' joined the room.');room_save($r);return ['code'=>$code,'playerId'=>$p['id'],'token'=>$p['token']];});out($result);}

$code=code6($_GET['code']??'');
$result=with_lock($code,function()use($action){$r=room_get(code6($_GET['code']??''));$me=auth_room($r);if(!presence_alive($r['hostId'])&&$r['players'][$me]['id']!==$r['hostId']){transfer_host($r);room_save($r);$me=pidx($r,$_SERVER['HTTP_X_PLAYER_ID']??'');}if(advance($r))room_save($r);$p=$r['players'][$me];
if($action==='state'&&$_SERVER['REQUEST_METHOD']==='GET')return public_state($r,$me);
if($action==='settings'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can change settings.',403);if($r['status']!=='lobby')fail('Settings are locked after the game starts.');$b=body();$r['roundLimit']=validate_setting($b['rounds']??$r['roundLimit'],BOB_ROUND_OPTIONS,'round count');$r['voteSeconds']=validate_setting($b['voteSeconds']??$r['voteSeconds'],BOB_VOTE_OPTIONS,'vote timer');$r['revealSeconds']=validate_setting($b['revealSeconds']??$r['revealSeconds'],BOB_REVEAL_OPTIONS,'reveal timer');$r['autoAdvance']=!empty($b['autoAdvance']);room_save($r);return public_state($r,$me);}
if($action==='lock'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can lock the lobby.',403);if($r['status']!=='lobby')fail('The lobby is already closed.');$r['joinLocked']=!$r['joinLocked'];system_msg($r,$r['joinLocked']?'Lobby locked.':'Lobby reopened.');room_save($r);return public_state($r,$me);}
if($action==='start'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can start the game.',403);if($r['status']!=='lobby')fail('The game has already started.');if(count(active_players($r))<BOB_MIN_PLAYERS)fail('At least two players are required.');$r['joinLocked']=true;begin_round($r);system_msg($r,'The game started. Lock in BUD or BLUFF.');room_save($r);return public_state($r,$me);}
if($action==='vote'&&$_SERVER['REQUEST_METHOD']==='POST'){if($r['status']!=='voting')fail('Voting is closed.');if(empty($p['active']))fail('You are no longer active in this game.',403);if($r['players'][$me]['vote']!==null)fail('Your vote is already locked.');$b=body();$v=strtoupper(trim(strval($b['vote']??'')));if(!in_array($v,['BUD','BLUFF'],true))fail('Vote must be BUD or BLUFF.');$dbl=!empty($b['double']);if($dbl&&$r['players'][$me]['doubleUsed'])fail('Double Hit was already used.');$r['players'][$me]['vote']=$v;$r['players'][$me]['voteDouble']=$dbl;$r['lastEvent']=['id'=>rid(8),'type'=>'vote-locked','playerId'=>$p['id']];if(all_voted($r))reveal_round($r);room_save($r);return public_state($r,$me);}
if($action==='reveal'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can force the reveal.',403);if($r['status']!=='voting')fail('This round is not accepting votes.');reveal_round($r);room_save($r);return public_state($r,$me);}
if($action==='next'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can advance the round.',403);if($r['status']!=='reveal')fail('The round is not ready to advance.');if(now_ms()<intval($r['revealStartedAt']??0)+2000)fail('Give the room a moment to see the reveal.');next_round($r);room_save($r);return public_state($r,$me);}
if($action==='chat'&&$_SERVER['REQUEST_METHOD']==='POST'){rate_limit('chat',20,30);$b=body();$t=clean_text($b['text']??'');if($t==='')fail('Message is empty.');$r['chat'][]=['id'=>rid(8),'kind'=>'player','playerId'=>$p['id'],'name'=>$p['name'],'text'=>$t,'at'=>now_ms()];if(count($r['chat'])>80)$r['chat']=array_slice($r['chat'],-80);room_save($r);return public_state($r,$me);}
if($action==='kick'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can remove players.',403);if($r['status']!=='lobby')fail('Players can only be removed in the lobby.');$b=body();$target=strval($b['playerId']??'');$ti=pidx($r,$target);if($ti<0||$target===$r['hostId'])fail('That player cannot be removed.');$name=$r['players'][$ti]['name'];array_splice($r['players'],$ti,1);system_msg($r,$name.' was removed from the lobby.');room_save($r);$me=pidx($r,$p['id']);return public_state($r,$me);}
if($action==='leave'&&$_SERVER['REQUEST_METHOD']==='POST'){if($r['status']==='lobby'){array_splice($r['players'],$me,1);}else{$r['players'][$me]['active']=false;$r['players'][$me]['vote']=null;$r['players'][$me]['voteDouble']=false;}system_msg($r,$p['name'].' left the room.');if(count(active_players($r))===0){room_save($r);return ['left'=>true];}if($p['id']===$r['hostId'])transfer_host($r);if(in_array($r['status'],['voting','reveal'],true)&&count(active_players($r))<BOB_MIN_PLAYERS)finish_game($r,'not-enough-players');elseif($r['status']==='voting'&&all_voted($r))reveal_round($r);room_save($r);return ['left'=>true];}
if($action==='rematch'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can start a rematch.',403);if($r['status']!=='finished')fail('The game is not finished.');$r['players']=array_values(array_filter($r['players'],fn($x)=>!empty($x['active'])));foreach($r['players'] as &$x){$x['score']=0;$x['streak']=0;$x['bestStreak']=0;$x['doubleUsed']=false;$x['vote']=null;$x['voteDouble']=false;}unset($x);$r['round']=0;$r['deckOrder']=shuffle_idx(count(cards()));$r['status']='lobby';$r['joinLocked']=false;$r['roundSummary']=null;$r['voteEndsAt']=null;$r['revealEndsAt']=null;$r['finishReason']=null;system_msg($r,'Rematch lobby opened.');room_save($r);$me=pidx($r,$p['id']);return public_state($r,$me);}
if($action==='end'&&$_SERVER['REQUEST_METHOD']==='POST'){if($p['id']!==$r['hostId'])fail('Only the host can end the game.',403);finish_game($r,'ended-by-host');room_save($r);return public_state($r,$me);}fail('Unsupported request.',405);});out(is_array($result)?$result:['ok'=>true]);
